spring:
  application:
    name: eureka-service
server:
  port: 2001
eureka:
  server:
    enable-self-preservation: false # eureka的自我保存状态，心中失败的比例，在15分钟内是否低于85%，如何出现了低于的情况，
    #Eureka Server会将当前的实例注册信息保护起来，同时提示一个警告，一旦进入保护模式，Eureka Server将会尝试保护其服务注册表中的信息，
    #不再删除服务注册表中的数据。也就是不会注销任何微服务
  instance:
    hostname: eureka1 #eureka 集群服务器之间，通过hostname 来区分
    lease-expiration-duration-in-seconds: 90 #最后一次心跳后，间隔多久认定微服务不可用，默认90s
  client:
    register-with-eureka: false #不向自身注册
    fetch-registry: false #不从自身拉取注册信息
